# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-14 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='spec',
        ),
        migrations.AddField(
            model_name='goods',
            name='aoi',
            field=models.IntegerField(default=1, verbose_name='库存数量'),
        ),
    ]
