# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-29 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180829_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='version',
            field=models.IntegerField(default=1, verbose_name='版本号'),
        ),
    ]
