# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-31 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_goods_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccount', models.PositiveIntegerField(verbose_name='数量')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='交易下单时间')),
                ('done_date', models.DateTimeField(null=True, verbose_name='交易完成时间')),
                ('comment', models.CharField(max_length=200, verbose_name='评论')),
                ('isDone', models.BooleanField(default=False, verbose_name='付款完成')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
